name 'cups'
author 'mosen'
description 'Zenoss core device management'
source 'https://github.com/mosen/puppet-zenoss.git'
summary 'With this module you can add/remove devices from the Zenoss monitoring system.'
license 'GPLv3'
version '0.0.1'
