name 'mosen-zenoss'
author 'mosen'
description 'Zenoss core device management'
source 'https://github.com/mosen/puppet-zenoss.git'
summary 'With this module you can add/remove devices from the Zenoss monitoring system.'
license 'MIT'
version '0.0.1'
dependency 'puppetlabs/rabbitmq'
dependency 'puppetlabs/firewall'
dependency 'puppetlabs/mysql'
dependency 'stahnma/epel'
dependency 'yguenane/repoforge'